// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsQlAicw5AxM7wmiODeHe6nYNZ32RZ3PE',
    appId: '1:925432021988:web:79b41b2f4176701c617df1',
    messagingSenderId: '925432021988',
    projectId: 'final-ffda7',
    authDomain: 'final-ffda7.firebaseapp.com',
    storageBucket: 'final-ffda7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHKJgRzvC55C63sTQwv0WV1cgEPYo7GxM',
    appId: '1:925432021988:android:ed1dbda9b66c8d7c617df1',
    messagingSenderId: '925432021988',
    projectId: 'final-ffda7',
    storageBucket: 'final-ffda7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4hRxmgvXUPS0LIUaxSabIrkWs8Sbj8dc',
    appId: '1:925432021988:ios:0238bfcbfc9df5e1617df1',
    messagingSenderId: '925432021988',
    projectId: 'final-ffda7',
    storageBucket: 'final-ffda7.appspot.com',
    iosBundleId: 'com.example.firebaseTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4hRxmgvXUPS0LIUaxSabIrkWs8Sbj8dc',
    appId: '1:925432021988:ios:772e1dc8bb36cb4b617df1',
    messagingSenderId: '925432021988',
    projectId: 'final-ffda7',
    storageBucket: 'final-ffda7.appspot.com',
    iosBundleId: 'com.example.finalProject.RunnerTests',
  );
}
