// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDFa5JBK4C_7r0DaMHW0xbt6YdAxFy7L0',
    appId: '1:995708666308:web:a27ebf2f636c6e897be491',
    messagingSenderId: '995708666308',
    projectId: 'nomad-final-9220',
    authDomain: 'nomad-final-9220.firebaseapp.com',
    storageBucket: 'nomad-final-9220.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKdBfc2dn9IW-PGbEyK44hFL193-5rY-g',
    appId: '1:995708666308:android:4a03ae4e1f1348947be491',
    messagingSenderId: '995708666308',
    projectId: 'nomad-final-9220',
    storageBucket: 'nomad-final-9220.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVDV2vzGfn86qA8zinxzplBHY9UB9UA9E',
    appId: '1:995708666308:ios:3b833c71e0c69af87be491',
    messagingSenderId: '995708666308',
    projectId: 'nomad-final-9220',
    storageBucket: 'nomad-final-9220.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVDV2vzGfn86qA8zinxzplBHY9UB9UA9E',
    appId: '1:995708666308:ios:3239f4b9b2e055a07be491',
    messagingSenderId: '995708666308',
    projectId: 'nomad-final-9220',
    storageBucket: 'nomad-final-9220.appspot.com',
    iosBundleId: 'com.example.finalProject.RunnerTests',
  );
}
